name: CI-CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  # Local Build and Test
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "zulu"
          cache: "maven"

      - name: Build and Analyze with SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub automatically
        run: | 
          mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.qualitygate.wait=true  

  # Infrastructure Deployment
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-test
    permissions:
      id-token: write
      contents: read
    env:
      TF_LOG: DEBUG
      TF_VAR_project_name: ${{ github.event.repository.name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        # pinned to v4 stable
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Setup Terraform
        # pinned to v3.1.2
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: "1.10.0"

      - name: Terraform Init
        run: |
          BUCKET_NAME="${{ github.event.repository.name }}-tfstate-${{ github.repository_owner }}"
          terraform init -input=false -backend-config="bucket=${BUCKET_NAME}"
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./terraform
